import type { Metadata } from 'next'; 
import { Inter } from 'next/font/google';
import './globals.css';
import SessionWrapper from '@/components/sessionwrapper/sessionwrapper';

const inter = Inter({ subsets: ['latin'] }); 

export const metadata: Metadata = {
  title: 'Create Next Auth',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
