import '../globals.css'

export const metadata = {
  title: 'Blog page',
  description: 'Generated by Next.js',
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <section>{children}</section>
  )
}
